version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
